baseURL = 'https://shoujo.ink'
hasCJKLanguage = true
title = "Mayo's Blog"
theme = "kagami"

languageCode = "zh-Hans"

paginate = 10
enableEmoji = true

googleAnalytics = "G-JKVXF5HSKT"

[permalinks]
posts = "/:year/:month/:slug"

[params]
mainSections = ["posts"]
description = "Mayo's Blog"
title = "Mayo's Blog"
favicon_url = "https://github.com/mayocream.png"

[params.social]
github = "mayocream"

[[menu.main]]
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 1

[taxonomies]
tag = "tags"
series = "series"

[markup.highlight]
codeFences = false

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true

[markup.goldmark.parser]
autoHeadingID = true
autoHeadingIDType = 'github'

[markup.goldmark.parser.attribute]
block = false
title = true
