baseURL = 'https://shoujo.ink'
hasCJKLanguage = true
title = "Mayo's Blog"
theme = "kagami"

languageCode = "zh-Hans"

paginate = 10
enableEmoji = true

[permalinks]
posts = "/:year/:month/:slug"

[params]
mainSections = ["posts"]
description = "Mayo's Blog"
title = "Mayo's Blog"

[params.social]
github = "mayocream"
twitter = "Freeze_Mayo"

[[menu.main]]
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 1

[taxonomies]
tag = "tags"
series = "series"

[markup.highlight]
codeFences = false
