baseURL = '/'
hasCJKLanguage = true
title = "Mayo's Blog"
theme = "axiom"

languageCode = "en-us"
defaultContentLanguage = "en"

paginate = 10
canonifyURLs = false
# summaryLength = 40
rssLimit = 100
enableEmoji = true
enableRobotsTXT = true
pluralizelisttitles = false

[permalinks]
posts = "/:year/:month/:slug"

[params]
mainSections = ["posts"]
copyrightYear = 2020
disableThemeAttribution = true
# Go Reference time: Mon Jan 2 15:04:05 MST 2006
dateFormat = "Jan 2, 2006 3:04PM"
highlight = "dark"
# contentEditBaseURL = "https://github.com/haya14busa/haya14busa.dev/blob/master/content/"
# discussionDefaultURL = "https://github.com/haya14busa/haya14busa.dev/discussions/categories/posts"

[params.brand]
# Just domain name, no www
domain = "example.com"
# Contact email address
email = "info@example.com"

[taxonomies]
tag = "tags"

[[menu.main]]
url = "/posts/"
name = "Posts"
weight = 1

[[menu.foot]]
url = "/posts/"
name = "Posts"
weight = 1

[[menu.foot]]
url = "/about/"
name = "About"
weight = 2

[markup.goldmark.extensions]
definitionList = false
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = false
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.parser]
attribute = false
[markup.highlight]
codeFences = true
noClasses = false
tabWidth = 4

[languages.zh]
[languages.en]